disabled     = false
languageCode = "en"
languageName = "English"
title        = "N. Redick"
weight       = 1

[params]
    dateFormat  = "2 January 2006"
    displayName = "EN"
    isoCode     = "en"
    rtl         = false

    [[params.author.links]]
        bluesky        = "https://bsky.app/profile/nredick.bsky.social"
        email          = "mailto:nrredick@ucdavis.edu"
        github         = "https://github.com/nredick"
        google-scholar = "https://scholar.google.com/citations?user=lvM_6HMAAAAJ&hl=en"
        linkedin       = "https://www.linkedin.com/in/nredick"
        orcid          = "https://orcid.org/0009-0005-5028-5299"

["params.author"]
    bio      = """"""
    headline = "MSc student in Geophysics"
    image    = "avatar.jpg"
    name     = "Nathalie R. Redick"
    pronouns = "she/her"
