disabled     = false
languageCode = "en"
languageName = "English"
title        = "N. Redick"
weight       = 1

[params]
    dateFormat  = "2 January 2006"
    displayName = "EN"
    isoCode     = "en"
    rtl         = false
