[[main]]
    none = "none"

[[main]]
    identifier = "posts"
    name       = "Posts"
    weight     = 12

[[main]]
    identifier = "docs"
    name       = "Docs"
    pageRef    = "docs"
    parent     = "posts"
    weight     = 12

[[main]]
    identifier = "notes"
    name       = "Notes"
    pageRef    = "notes"
    parent     = "posts"
    weight     = 20

[[main]]
    identifier = "qx9XY0i3mw"
    name       = "Papers"
    pageRef    = "papers"
    weight     = 10

[[main]]
    identifier = "Xt65JPJG1J"
    name       = "Talks"
    pageRef    = "talks"
    weight     = 11

[[footer]]
    none = "none"
