[[main]]
none = "none"

[[main]]
name = "Papers"
pageRef = "papers"
identifier = "qx9XY0i3mw"
weight = 9_999

[[main]]
name = "Talks"
pageRef = "talks"
identifier = "Xt65JPJG1J"
weight = 9_999

[[footer]]
none = "none"
