advertisement                 = {}
autoSwitchAppearance          = true
buymeacoffee                  = {}
colorScheme                   = "avocado"
defaultAppearance             = "light"
disableImageOptimization      = false
disableImageOptimizationMD    = false
disableTextInHeader           = false
enableA11y                    = false
enableCodeCopy                = false
enableSearch                  = true
fathomAnalytics               = {}
fingerprintAlgorithm          = "sha512"
firebase                      = {}
forgejoDefaultServer          = "https://v11.next.forgejo.org"
giteaDefaultServer            = "https://git.fsfe.org"
highlightCurrentMenuArea      = true
replyByEmail                  = false
rssnext                       = {}
selineAnalytics               = {}
smartTOC                      = false
smartTOCHideUnfocusedChildren = true
umamiAnalytics                = {}
verification                  = {}

[header]
    layout = "fixed-fill-blur"

[footer]
    showAppearanceSwitcher = true
    showCopyright          = true
    showMenu               = true
    showScrollToTop        = true
    showThemeAttribution   = true

[homepage]
    cardView               = false
    cardViewScreenWidth    = false
    disableHeroImageFilter = false
    homepageImage          = "background.png"
    layout                 = "academic"
    layoutBackgroundBlur   = false
    showMoreLink           = false
    showMoreLinkDest       = "/notes/"
    showRecent             = false
    showRecentItems        = 5

[article]
    editAppendPath              = true
    invertPagination            = false
    layoutBackgroundBlur        = true
    layoutBackgroundHeaderSpace = true
    seriesOpened                = false
    showAuthor                  = true
    showAuthorsBadges           = false
    showBreadcrumbs             = false
    showCategoryOnly            = false
    showDate                    = true
    showDateOnlyInArticle       = false
    showDateUpdated             = false
    showDraftLabel              = true
    showEdit                    = false
    showHeadingAnchors          = true
    showHero                    = false
    showLikes                   = false
    showPagination              = true
    showReadingTime             = true
    showTableOfContents         = true
    showTaxonomies              = false
    showViews                   = false
    showWordCount               = true
    showZenMode                 = false

[list]
    cardView                    = false
    cardViewScreenWidth         = false
    constrainItemsWidth         = false
    groupByYear                 = true
    layoutBackgroundBlur        = true
    layoutBackgroundHeaderSpace = true
    orderByWeight               = false
    showBreadcrumbs             = false
    showCards                   = false
    showHero                    = false
    showLikes                   = false
    showSummary                 = false
    showTableOfContents         = false
    showViews                   = false

[sitemap]
    excludedKinds = ["taxonomy", "term"]

[taxonomy]
    cardView            = false
    showBreadcrumbs     = false
    showHero            = false
    showLikes           = false
    showTableOfContents = false
    showTermCount       = true
    showViews           = false

[term]
    cardView            = false
    cardViewScreenWidth = false
    groupByYear         = false
    showBreadcrumbs     = false
    showHero            = false
    showLikes           = false
    showTableOfContents = true
    showViews           = false
