advertisement                 = {}
autoSwitchAppearance          = false
buymeacoffee                  = {}
colorScheme                   = "blowfish"
defaultAppearance             = "dark"
disableImageOptimization      = false
disableImageOptimizationMD    = false
disableTextInHeader           = false
enableA11y                    = false
enableCodeCopy                = true
enableSearch                  = true
fathomAnalytics               = {}
fingerprintAlgorithm          = "sha512"
firebase                      = {}
forgejoDefaultServer          = "https://v11.next.forgejo.org"
giteaDefaultServer            = "https://git.fsfe.org"
highlightCurrentMenuArea      = true
replyByEmail                  = false
rssnext                       = {}
selineAnalytics               = {}
smartTOC                      = false
smartTOCHideUnfocusedChildren = true
umamiAnalytics                = {}
verification                  = {}

[header]
    layout = "fixed-fill-blur"

[footer]
    showAppearanceSwitcher = false
    showCopyright          = true
    showMenu               = true
    showScrollToTop        = true
    showThemeAttribution   = true

[homepage]
    cardView               = false
    cardViewScreenWidth    = false
    disableHeroImageFilter = false
    homepageImage          = "background.png"
    layout                 = "academic"
    layoutBackgroundBlur   = false
    showMoreLink           = false
    showMoreLinkDest       = "/posts/"
    showRecent             = false
    showRecentItems        = 5

[article]
    editAppendPath              = true
    invertPagination            = false
    layoutBackgroundBlur        = true
    layoutBackgroundHeaderSpace = true
    seriesOpened                = false
    showAuthor                  = false
    showAuthorsBadges           = false
    showBreadcrumbs             = true
    showCategoryOnly            = false
    showDate                    = true
    showDateOnlyInArticle       = false
    showDateUpdated             = false
    showDraftLabel              = true
    showEdit                    = false
    showHeadingAnchors          = true
    showHero                    = false
    showLikes                   = false
    showPagination              = true
    showReadingTime             = true
    showTableOfContents         = true
    showTaxonomies              = true
    showViews                   = false
    showWordCount               = true
    showZenMode                 = false

[list]
    cardView                    = false
    cardViewScreenWidth         = false
    constrainItemsWidth         = false
    groupByYear                 = true
    layoutBackgroundBlur        = true
    layoutBackgroundHeaderSpace = true
    orderByWeight               = false
    showBreadcrumbs             = true
    showCards                   = false
    showHero                    = false
    showLikes                   = false
    showSummary                 = false
    showTableOfContents         = true
    showViews                   = false

[sitemap]
    excludedKinds = ["taxonomy", "term"]

[author]
    bio      = ""
    headline = "MSc student in Geophysics"
    image    = "avatar.jpg"
    name     = "Nathalie Redick"
    pronouns = "she/her"

    [[author.links]]
        bluesky        = "https://bsky.app/profile/nredick.bsky.social"
        email          = "mailto:nrredick@ucdavis.edu"
        github         = "https://github.com/nredick"
        google-scholar = "https://scholar.google.com/citations?user=lvM_6HMAAAAJ&hl=en"
        linkedin       = "https://www.linkedin.com/in/nredick"
        orcid          = "https://orcid.org/0009-0005-5028-5299"

[taxonomy]
    cardView            = false
    showBreadcrumbs     = false
    showHero            = false
    showLikes           = false
    showTableOfContents = false
    showTermCount       = true
    showViews           = false

[term]
    cardView            = false
    cardViewScreenWidth = false
    groupByYear         = false
    showBreadcrumbs     = false
    showHero            = false
    showLikes           = false
    showTableOfContents = true
    showViews           = false
